# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_apropved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ir', 'In Review'), ('ap', 'Approved'), ('de', 'Deleted')], default='ir', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to=photo.models.PhotoUpload.path_and_rename)),
            ],
        ),
    ]
