# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoupload',
            name='date_apropved',
        ),
    ]
