# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photoupload_date_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=photo.models.PhotoUpload.path_and_rename, validators=[photo.models.PhotoUpload.file_size]),
        ),
    ]
