# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20170519_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='date_approved',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoupload',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
