# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_auto_20170519_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='date_deleted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
