# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20170519_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='status',
            field=models.CharField(choices=[('ir', 'In Review'), ('ap', 'Approved'), ('tr', 'Trash')], default='ir', max_length=2),
        ),
    ]
